// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TradeService.DataRepository;

namespace TradeService.DataRepository.Migrations
{
    [DbContext(typeof(TradeDbContext))]
    partial class TradeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TradeService.Model.Entities.Buyer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SalesIds")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Buyer");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b0000001-e3ea-4063-9089-48cffd3f56bc"),
                            IsDeleted = false,
                            Name = "Роман Васильев",
                            SalesIds = "[]"
                        },
                        new
                        {
                            Id = new Guid("b0000002-479c-4e1f-a55c-2220e913d934"),
                            IsDeleted = false,
                            Name = "Игорь Вернов",
                            SalesIds = "[]"
                        },
                        new
                        {
                            Id = new Guid("b0000003-b0c4-4267-96e6-fe74ffe21424"),
                            IsDeleted = false,
                            Name = "Надежда Иванова",
                            SalesIds = "[]"
                        },
                        new
                        {
                            Id = new Guid("b0000004-ac13-47dc-b614-fc06ebf47c9b"),
                            IsDeleted = false,
                            Name = "Кирилл Сергеев",
                            SalesIds = "[]"
                        });
                });

            modelBuilder.Entity("TradeService.Model.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a0000001-17c3-4fcc-8cbf-03a9cdfcee4c"),
                            IsDeleted = false,
                            Name = "Лампочка",
                            Price = 100f
                        },
                        new
                        {
                            Id = new Guid("a0000002-188c-4fc9-8311-37e7eff4dbcf"),
                            IsDeleted = false,
                            Name = "Фонарик",
                            Price = 435f
                        },
                        new
                        {
                            Id = new Guid("a0000003-df02-43a6-8d2a-0106062d5ac9"),
                            IsDeleted = false,
                            Name = "Люстра",
                            Price = 3153f
                        },
                        new
                        {
                            Id = new Guid("a0000004-9106-413d-b45a-ac98be9bb38d"),
                            IsDeleted = false,
                            Name = "Розетка",
                            Price = 150f
                        });
                });

            modelBuilder.Entity("TradeService.Model.Entities.Sale", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BuyerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("Date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("SalesData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SalesPointId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeSpan>("Time")
                        .HasColumnType("time");

                    b.Property<float>("TotalAmount")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Sale");
                });

            modelBuilder.Entity("TradeService.Model.Entities.SalesPoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProvidedProducts")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SalesPoint");

                    b.HasData(
                        new
                        {
                            Id = new Guid("af000001-1644-4188-a3ff-3dd392de686e"),
                            IsDeleted = false,
                            Name = "Электрон",
                            ProvidedProducts = "[{\"ProductId\":\"a0000001-17c3-4fcc-8cbf-03a9cdfcee4c\",\"ProductQuantity\":130},{\"ProductId\":\"a0000002-188c-4fc9-8311-37e7eff4dbcf\",\"ProductQuantity\":25}]"
                        },
                        new
                        {
                            Id = new Guid("af000002-ca00-4c80-8581-63ecc5ae86cb"),
                            IsDeleted = false,
                            Name = "Планета 220",
                            ProvidedProducts = "[{\"ProductId\":\"a0000001-17c3-4fcc-8cbf-03a9cdfcee4c\",\"ProductQuantity\":65},{\"ProductId\":\"a0000004-9106-413d-b45a-ac98be9bb38d\",\"ProductQuantity\":3}]"
                        },
                        new
                        {
                            Id = new Guid("af000003-41bc-4f79-84f9-db1c6507c95c"),
                            IsDeleted = false,
                            Name = "220v",
                            ProvidedProducts = "[{\"ProductId\":\"a0000002-188c-4fc9-8311-37e7eff4dbcf\",\"ProductQuantity\":34},{\"ProductId\":\"a0000003-df02-43a6-8d2a-0106062d5ac9\",\"ProductQuantity\":5},{\"ProductId\":\"a0000004-9106-413d-b45a-ac98be9bb38d\",\"ProductQuantity\":60}]"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
